import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Monito - Pet Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='flex flex-col overflow-x-hidden'>
      <body className='flex flex-col overflow-hidden'>{children}</body>
    </html>
  )
}
